version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: node
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          command: 
      - run:
          command: ./setup.sh
      - run:
          name: run server 
          command: node app.js
          background: true
      - run:
          name: run proxy 
          command: node proxy.js
          background: true
      - run: # run coverage report
          name: test
          command: curl https://local.server/

